FROM oven/bun:1
WORKDIR /app

# Instalar dependencias
COPY package.json package-lock.json* bun.lockb* ./
RUN bun install

# Copiar código fuente
COPY . .

EXPOSE 3000

# Usar el script de desarrollo de Next.js
CMD ["bun", "run", "dev"]
